-- this file is autogenerated by WowUp (app) at Mon Oct 11 2021 02:16:46 GMT+0300 (Eastern European Summer Time)
WOWUP_DATA = {}
WOWUP_DATA.icon = "Interface/AddOns/wowup_data_addon/ldbicon"
WOWUP_DATA.addonManagerName = "WowUp"
WOWUP_DATA.addonManagerColorRGB = {232/255,205/255,134/255}
WOWUP_DATA.addonManagerNameSlashCommand = "/wowup"
WOWUP_DATA.updateAddonsList = {
}
